"""Add user_id FKs

Revision ID: 0a71ebf7c79b
Revises: c2051c700958
Create Date: 2025-12-21 08:49:19.402479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a71ebf7c79b'
down_revision: Union[str, None] = 'c2051c700958'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaderboard', sa.Column('user_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_leaderboard_user_id'), 'leaderboard', ['user_id'], unique=False)
    
    # --- Data Backfill Start ---
    # Update leaderboard entries to link to users via username
    op.execute("""
        UPDATE leaderboard 
        SET user_id = users.id 
        FROM users 
        WHERE leaderboard.username = users.username
    """)
    
    # Update sessions to link to users via username (assuming user_id was previously username or empty)
    # If sessions.user_id already held UUIDs, this is fine. If it held usernames, we need to fix it.
    # The previous model had user_id as String, usually storing UUID, but let's ensure consistency.
    # However, since sessions is transient, we might just trust the existing IDs if they are valid.
    # But let's be safe: if user_id matches a username, update it to the UUID.
    op.execute("""
        UPDATE sessions
        SET user_id = users.id
        FROM users
        WHERE sessions.username = users.username
        AND (sessions.user_id IS NULL OR sessions.user_id = users.username)
    """)
    # --- Data Backfill End ---

    op.create_foreign_key(None, 'leaderboard', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'sessions', 'users', ['user_id'], ['id'])
    
    op.alter_column('user_groups', 'username',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('user_groups', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    
    # Commented out index changes to avoid unintentional modification of Unique constraints
    # op.drop_index(op.f('ix_users_email'), table_name='users')
    # op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    # op.drop_index(op.f('ix_users_username'), table_name='users')
    # op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_users_username'), table_name='users')
    # op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # op.drop_index(op.f('ix_users_email'), table_name='users')
    # op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    
    op.alter_column('user_groups', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user_groups', 'username',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_constraint(None, 'leaderboard', type_='foreignkey')
    op.drop_index(op.f('ix_leaderboard_user_id'), table_name='leaderboard')
    op.drop_column('leaderboard', 'user_id')
    # ### end Alembic commands ###
